name: deploy-page

on:
  push:
    branches:
      - main

jobs:
  build:
    permissions:
      # NOTE: give permission to push commits
      contents: write
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.21
      id: go

    - name: Checkout
      uses: actions/checkout@v2

    - name: Build WASM binaries
      run: ./gen_wasm.sh

    - name: Set up Node
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Build frontend
      # HACK: pass env to fix link path
      env:
        GITHUB_PAGES: true
      run: |
        npm install
        npm run build

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
